# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uidemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(736, 569)
        self.button_RED = QtWidgets.QCheckBox(form)
        self.button_RED.setGeometry(QtCore.QRect(150, 120, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_RED.setFont(font)
        self.button_RED.setObjectName("button_RED")
        self.button_GREEN = QtWidgets.QCheckBox(form)
        self.button_GREEN.setGeometry(QtCore.QRect(150, 180, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_GREEN.setFont(font)
        self.button_GREEN.setObjectName("button_GREEN")
        self.button_BLUE = QtWidgets.QCheckBox(form)
        self.button_BLUE.setGeometry(QtCore.QRect(150, 240, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_BLUE.setFont(font)
        self.button_BLUE.setObjectName("button_BLUE")

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "PiHAT_UI"))
        self.button_RED.setText(_translate("form", "RED"))
        self.button_GREEN.setText(_translate("form", "GREEN"))
        self.button_BLUE.setText(_translate("form", "BLUE"))
